// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkNihudlsA3Q_zIyN3RBbXQkRtJdXsqAI',
    appId: '1:450764994912:web:92aef4c5b6c8ffa8e04605',
    messagingSenderId: '450764994912',
    projectId: 'moneymanage-12188',
    authDomain: 'moneymanage-12188.firebaseapp.com',
    storageBucket: 'moneymanage-12188.appspot.com',
    measurementId: 'G-M1K26WFNKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbXqtBLFvnMwVRVN9Fd7uL1qpTC6sUzBc',
    appId: '1:450764994912:android:eee9bcbab3ae96a4e04605',
    messagingSenderId: '450764994912',
    projectId: 'moneymanage-12188',
    storageBucket: 'moneymanage-12188.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqxxsa6P7I7guQiP02Gh-kthXLRkZ4TmA',
    appId: '1:450764994912:ios:e7d941a62ab16e10e04605',
    messagingSenderId: '450764994912',
    projectId: 'moneymanage-12188',
    storageBucket: 'moneymanage-12188.appspot.com',
    iosBundleId: 'com.example.money',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqxxsa6P7I7guQiP02Gh-kthXLRkZ4TmA',
    appId: '1:450764994912:ios:df8fdb03ad195c6fe04605',
    messagingSenderId: '450764994912',
    projectId: 'moneymanage-12188',
    storageBucket: 'moneymanage-12188.appspot.com',
    iosBundleId: 'com.example.money.RunnerTests',
  );
}
